#!/usr/bin/env bash

# Enter a URL, spits out the contents of <title></title> on that page.
# The idea is to quickly store a link alongside the title to:
#   - keep track of articles to read in a text file
#   - citing technical references 
#   - really whatever
#
# Depends on:
#   - htmlq (https://github.com/mgdm/htmlq#installation)

url=$1
if [ -z $url ]; then
    # fail silently in UNIX style
    exit 1
fi

# TODO should probably use -L to follow redirects
# TODO should check response code here and fail if not 200
curl -s $url | htmlq "title" --text
echo $url
echo # new line is nice for appending to files
